### ISSUE TITLE
Examples on website are broken

### ISSUE THREAD

**Issue by timdown** [bvaughn/react-resizable-panels#206]
Firstly, thanks for finishing the pixel size work, which looks promising. However, I think there are some rough edges in 0.0.56. I've noticed the following problems with the examples on the website, some of which I've also seen on the application I'm working on:

- All pages: resizing seems to snap only to the maximum or minimum size (at least in most cases)
- Collapsible panels: the resizer seems to be stuck on the right-hand side
- Pixel-based layouts: resizers have no effect

Additionally, there's an error when calling `expand()` or `collapse()` on a panel via the imperative API in an effect that runs after first render:

https://codesandbox.io/s/lively-surf-jq5pzc?file=/src/App.js

**Comment by bvaughn** [comment]
Oh that's embarrassing. I probably broke something by making a last minute change yesterday for the e2e test. I'll look into it soon!

**Comment by bvaughn** [comment]
Interestingly, the bug doesn't repro locally (localhost running the latest version of main).

**Comment by bvaughn** [comment]
Ah! The problem is that I'm rendering the `data-panel-group-id` attribute conditionally (dev only) for `PanelGroup`. Wow what an oversight.

**Comment by bvaughn** [comment]
Thanks so much for reporting this issue. I think it's been fixed in 0.0.57. (There may be other regressions related to the large rewrite, but at least the one you reported has been resolved.)

**Comment by bvaughn** [comment]
Thanks so much for reporting this issue. I think it's been fixed in 0.0.57. (There may be other regressions related to the large rewrite, but at least the one you reported has been resolved.)

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

**Comment by timdown** [comment]
> Ah! The problem is that I'm rendering the `data-panel-group-id` attribute conditionally (dev only) for `PanelGroup`. Wow what an oversight.

Hey, we've all done that kind of thing :smile: Thanks for fixing it so quickly. I'll let you know if I find anything else.

**Comment by bvaughn** [comment]
Thanks!

**Comment by timdown** [comment]
I'm still seeing the `expand()`/`collapse()` issue: https://codesandbox.io/s/gracious-cannon-h5stq4. I guess it's a slightly odd thing to be expanding or collapsing a panel straight after the initial render, but it worked in previous versions.
